# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338a018cc769e5c6e5bc7f8791c97005e7215294e1755a47e3cf7320989a3016a44a6e4ea58a142dee71c943609e37adb2cc6e9418cf719d0765816bcf6859b3

test:
  secret_key_base: 64a295435c0ccebd883904ff7b0b1c10f3190d043aea065f41edffd295eeb4853885a70fd8424b5eb9a13cf7869be8747984996f00919e075892b1b115ce4552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
